theme: jekyll-theme-cayman
title: Expreta
show_downloads: true
github:
  zip_url: https://docs.google.com/presentation/d/e/2PACX-1vRC-a-bsmlxWfkGpyZBpOl25kwvbgsTmlXWSRe7h8BYUoPmcJIJuO-CMjvCV9IvDl9LYuEN3jRnEPBC/pub
